steps:
- uses: actions/checkout@v2
- name: run the action
  id: hello
  uses: ./
  with:
    myInput: 'ManuVino'
- name: output the memory
  run: |
    echo ${{ steps.hello.outputs.memory }}
    echo "total memory successfully output"
